name: Sitharal Video
description: Video blog for the sitharal.
url: 'https://sitharal.github.io/video'
baseurl: '/video'
email: jekyll-video@example.com
youtube: https://www.youtube.com/c/Sitharal TV
facebook: https://www.facebook.com/sitharaltv
google_analytics: 'UA-00000000-1'

################################################################
################################################################
gems:
  - jekyll-sitemap
sass:
  sass_dir: /assets/_sass
  style: :compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
collections:
  videos:
    output: true
    permalink: /:path/
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
  -
    scope:
      path: ''
      type: videos
    values:
      layout: video
